### PR TITLE
Spring layout 1

### PR DESCRIPTION
**Pull request by melvinalex7**
# Description 
A summary of the change 
Layout 1 for Deployed Client Website.

# Type of change 
- [ ] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
Briefly describe the root cause and analysis of the problem 

# Solution description
Describe your code changes in detail for reviewers. 
Explain the technical solution you have provided and how it fixes the issue.

# Tests 
All unit tests pass?

Builds successfully?
Yes.

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)
image
image
image
image

Provide steps in detail for reviewers to reproduce the expected result of the code changes.

-  Go to base1 folder under scholly folder.
-  Using npm run dev, the layout can be run in development mode.

# Relevant document/ link (if any) 
Any related documents could help reviewers to review this PR 

# Risk
Identity the risk level (low, medium, high) and indicate which component(s) will be affected if bugs exist.

### CODE REVIEW

**Review by aksh0001 — CHANGES_REQUESTED** [review]
Please combine scholly1 into scholly. We should have only one base app ideally.

**Comment by rsal0007** [comment]
> Please combine scholly1 into scholly. We should have only one base app ideally.

Agreed - Team Spring & Kunj are currently working on this and figuring out how to integrate layouts, colours and make the selection process dynamic under one base folder.

**Comment by aksh0001** [comment]
> > Please combine scholly1 into scholly. We should have only one base app ideally.
> 
> Agreed - Team Spring & Kunj are currently working on this and figuring out how to integrate layouts, colours and make the selection process dynamic under one base folder.

SGTM. Can we then do reviews after that's been implemented? We won't be able to merge this anyhow

**Comment by rsal0007** [comment]
> > > Please combine scholly1 into scholly. We should have only one base app ideally.
> > 
> > 
> > Agreed - Team Spring & Kunj are currently working on this and figuring out how to integrate layouts, colours and make the selection process dynamic under one base folder.
> 
> SGTM. Can we then do reviews after that's been implemented? We won't be able to merge this anyhow

Yep, valid point. Spring has its meeting tomorrow, so we'll make the necessary changes then and update accordingly.

**Comment by aksh0001** [comment]
As discussed over Slack, please integrate into the existing base app. Closing for now.

**Pull request closed without merging**
