### PR TITLE
Improve imported publication component

### PR DESCRIPTION
**Pull request by pmyip3**
# Description 
As title 

# Type of change 
- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring
- [ ] Documentation 
- [x] Improvement

# Problem
The current imported publication component is too large and not consistent to the publication page (link on a separate row and no hover effect)
image

# Solution description
- Make each publication component smaller
- add hover effect
- link can be opened by clicking on the publication title 

# Tests 
All unit tests pass? N/A

Builds successfully? Yes

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)
image

Provide steps in detail for reviewers to reproduce the expected result of the code changes.

# Relevant document/ link (if any) 
Any related documents could help reviewers to review this PR 

# Risk
Low, UI modification only

### CODE REVIEW

**Review by kdav108 — APPROVED** [review]
LGTM!

**Review by jfan0010 — APPROVED** [review]
lgtm

**Review by vgoh1 — APPROVED** [review]
Can we have the styling of the imported publication titles the same as the ones on the page? The titles all being in bold feels a bit overwhelming, especially if they're all links:
image
Can we have it consistent with this? 
image
otherwise looks great!

**Review by cyr17 — APPROVED** [review]
Ez

**Comment by pmyip3** [comment]
> Can we have the styling of the imported publication titles the same as the ones on the page? The titles all being in bold feels a bit overwhelming, especially if they're all links: image Can we have it consistent with this? image otherwise looks great!

image
Fixed!

**Pull request merged**
