### PR TITLE
Akash saggar/dynamic colours

### PR DESCRIPTION
**Pull request by AkashSaggar**
# Description 
Use theme option stored in database instead of a hard coded value for colour CSS files.

# Type of change 
- [ ] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
Currently uses a hardcoded value to pick which colour theme is used.

# Solution description
Just using the value from data.js and fakeData.js now

# Tests 
All unit tests pass? Yes
Builds successfully? Yes

# Risk
Low

### CODE REVIEW

**Review by melvinalex7 — COMMENTED** [review]
I don't think the Layout and Theme Selector functionality is working. 
image
I have updated the layout and theme before deployment however the deployed website had the default light theme and default layout 1
image

**Review by kdav108 — APPROVED** [review]
Looks great! Thanks for having my back with this PR 😂

**Comment by AkashSaggar** [comment]
@melvinalex7 Kunj and I have tried it and it seems to be working for us.
Could you try again and maybe wait a minute for GitHub pages to update?
After deployment sometimes it takes a minute for the site to update.

**Review by melvinalex7 — APPROVED** [review]
Showed some initial issues with the switching of layouts and themes. However, it seems to be working now.

**Review by vgoh1 — APPROVED** [review]

**Pull request merged**
