### PR TITLE
Publications page improvements based on uat

### PR DESCRIPTION
**Pull request by pmyip3**
# Description 
As Title

# Type of change 
- [ ] Bug fix
- [ ] New feature
- [x] Refactoring
- [ ] Documentation 
- [x] Improvement

# Problem
Refer to: https://docs.google.com/document/d/1xu01_5YBoS830fbq0I1YHU3Ify3N1bJyMAAGv6LlqpY/edit

# Solution description

_**Suggestion given in the user testing**_ 
Fixed: 
- spacing for “add author” button in publication form 
- asterisks for mandatory fields in publication form 
- font size 
- spacing in between publications row
- “Update layout” functionality is hard to understand 
   --> added a tooltip box when hoving the button 
- underline the publication title if it's a link
- Add author button might not be clear that it's adding a new line to add a new author
  --> changed the wording to 'Add More Author'

Did not fix: (reason below and welcome for discussion)
- "add” publications button needs to be distinguishable: Add symbol/ Different color button
   --> The Add symbol/ Different color button suggestions might cause inconsistency. I changed the button to "Add Publication(s)" to make it consistent with the team and achievement page for now

- Inconsistent buttons in publication(For group by and sort by)
  --> I think it's what the other websites do for this kind of button
image
image

_**Other consistency issue:**_ 
Fixed: 
- make the corner round like other pages 

Did not fix: 
- purple header like the current achievement page 
  --> tried to fix this one but the UI does not look nice to me, happy to use it tho if majority ppl agrees this layout
image

# Tests 
All unit tests pass? N/A

Builds successfully? Yes

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)
image
image

Provide steps in detail for reviewers to reproduce the expected result of the code changes.

# Relevant document/ link (if any) 
Refer to: https://docs.google.com/document/d/1xu01_5YBoS830fbq0I1YHU3Ify3N1bJyMAAGv6LlqpY/edit

# Risk
Low, UI modification only

### CODE REVIEW

**Review by jfan0010 — COMMENTED** [review]
Is it possible to make the `Add publication` button wrap text (like the `update layout` button) or align to the middle vertically?

Not necessarily related to this PR: when I'm on a narrower screen, the content is sticking with the sidebar, will there be an easy fix to include in this PR?

image

And I got this warning in console 🙈, doesn't affect the functionality though 
image

**Comment by pmyip3** [comment]
> Is it possible to make the `Add publication` button wrap text (like the `update layout` button) or align to the middle vertically?
> 
> Not necessarily related to this PR: when I'm on a narrower screen, the content is sticking with the sidebar, will there be an easy fix to include in this PR?
> 
> image
> 
> And I got this warning in console 🙈, doesn't affect the functionality though image

Fixed

**Review by jfan0010 — APPROVED** [review]
lgtm

**Review by vgoh1 — APPROVED** [review]
One nit but can be debated on: the page title is bigger than the researchify logo in the top left so it feels really big. Can it be smaller?

**Comment by pmyip3** [comment]
> One nit but can be debated on: the page title is bigger than the researchify logo in the top left so it feels really big. Can it be smaller?

Agree.... I will make a shared title CSS class in this PR

**Review by aksh0001 — APPROVED** [review]

**Comment by vgoh1** [comment]
@pmyip3 looks good to me

**Review by vgoh1 — APPROVED** [review]

**Pull request merged**
