### PR TITLE
Profile Picture Display Bug Fix

### PR DESCRIPTION
**Pull request by melvinalex7**
# Description 
A summary of the change 
Display Default Profile Image as Thumbnail on Header

# Type of change 
- [x] Bug fix
- [ ] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
Briefly describe the root cause and analysis of the problem 
Default Profile picture did not appear as a thumbnail on Header.
image

# Solution description
Describe your code changes in detail for reviewers. 
Explain the technical solution you have provided and how it fixes the issue.

# Tests 
All unit tests pass?

Builds successfully?
Yes

Attach screenshot of the expected result (e.g. UI of the website/ postman api call result/ database changes)
image

Provide steps in detail for reviewers to reproduce the expected result of the code changes.

# Relevant document/ link (if any) 
Any related documents could help reviewers to review this PR 

# Risk
Identity the risk level (low, medium, high) and indicate which component(s) will be affected if bugs exist.

### CODE REVIEW

**Review by jfan0010 — APPROVED** [review]
lgtm

**Comment by cyr17** [comment]
Wait wasn't this already handled by your commit in 235?

**Comment by vgoh1** [comment]
Isn't this already working in main when the user has no display picture? Can you give an example of how to reproduce this issue?

**Review by pmyip3 — APPROVED** [review]

**Comment by rpra0006** [comment]
> Isn't this already working in main when the user has no display picture? Can you give an example of how to reproduce this issue?

In PR#235[https://github.com/Researchify/Researchify/pull/235/files](url) @cyr17 set everything as profileData.object but forgot to do the same for profilePic.

**Review by rpra0006 — APPROVED** [review]

**Comment by melvinalex7** [comment]
> Wait wasn't this already handled by your commit in 235?

Well, I remember handling this issue in PR#235, but not sure what happened.

**Comment by melvinalex7** [comment]
> > Isn't this already working in main when the user has no display picture? Can you give an example of how to reproduce this issue?
> 
> In PR#235[https://github.com/Researchify/Researchify/pull/235/files](url) @cyr17 set everything as profileData.object but forgot to do the same for profilePic.

Nah, I was the one who did that. But quite not sure how it changed.

**Pull request merged**
